# Generated by Django 2.0.2 on 2018-03-03 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique_for_month=True)),
                ('body', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Date the post was originally created')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Date the post is published')),
                ('edit_date', models.DateTimeField(auto_now=True, verbose_name='Date post was edited, most recently')),
                ('snippet', models.TextField(verbose_name='Short section from the body of the text')),
                ('published', models.BooleanField(default=False, verbose_name='Whether the post is published, or still in edit')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
