# Generated by Django 2.0.2 on 2018-03-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180302_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(blank=True, verbose_name='Short section from the body of the text'),
        ),
    ]
